services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
        - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000

steps:
  - name: venv
    entrypoint: python
    args: [ "-m", "venv", "venv"]
  - name: env
    entrypoint: source
    args: ["venv/bin/activate"]
  - name: requirements
    entrypoint: pip
    args: [ "install", "-r", "requirements.txt", "--user" ]
  - name: pytest
    entrypoint: python
    args: [ "-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml" ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west9-docker.pkg.dev/$PROJECT_ID/oc-lettings-repo/oc-lettings-image:tag1', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west9-docker.pkg.dev/$PROJECT_ID/oc-lettings-repo/oc-lettings-image:tag1' ]
  - name: google/cloud-sdk
    args: [ 'gcloud', 'run', 'deploy', 'oc-lettings',
            '--image=europe-west9-docker.pkg.dev/${PROJECT_ID}/oc-lettings-repo/oc-lettings-image:tag1',
            '--region', 'europe-west9', '--platform', 'managed', '--port', '8080',
            '--allow-unauthenticated' ]
artifacts:
  objects:
    location: gs://oc-lettings_cloudbuild/
    paths:
      - ${SHORT_SHA}_test_log.xml
images:
  - 'europe-west9-docker.pkg.dev/$PROJECT_ID/oc-lettings-repo/oc-lettings-image:tag1'
