version: '3.10'

services:
  app:
    build:
      context: .
    pull_policy: build
    restart: always
    image: xevan/oc-lettings-repo
    volumes:
      - static-data:/vol/web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - SENTRY_DNS=$SENTRY_DNS
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  postgres-data:
  static-data:
