version: '3.10'

services:
  app:
    build:
      context: .
    pull_policy: build
    image: xevan/oc-lettings
    ports:
      - "7000:7000"
    environment:
      - DATABASE_URL=postgres://app:password@db:5432/oc_lettings
      - SENTRY_DNS=fake
      - DEBUG=1
      - PORT=7000
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=oc_lettings
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password

volumes:
  postgres-data:
