version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py wait_for_db &&
             python manage.py migrate --run-syncdb &&
             python manage.py wait_for_db &&
             python manage.py loaddata db.json &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=oc-lettings
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=supermdp
      - DEBUG=$DEBUG

volumes:
  postgres-data: