version: '3.10'

services:
  app:
    build:
      context: .
    pull_policy: build
    restart: always
    image: xevan/oc-lettings-repo
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER

volumes:
  postgres-data:

