version: '3.10'

services:
  app:
    build:
      context: .
    environment:
      DEBUG: $DEBUG
      PORT: $PORT
      SENTRY_DNS: $SENTRY_DNS
      DATABASE_URL: $DATABASE_URL
    pull_policy: build
    image: xevan/oc-lettings-repo:latest
    ports:
      - "7000:7000"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  postgres-data:
