version: '3.10'

services:
  app:
    build:
      context: .
    environment:
      - DEBUG=1
      - PORT=7000
      - SENTRY_DNS
      - DATABASE_URL=postgres://app:password@db:5432/oc-lettings
      - SECRET_KEY="fp9^593hsriajg_%=5trot9g!1qa@ew(o-1#@=&4%=hp46(s"
    image: xevan/oc-lettings-repo:latest
    ports:
      - "7000:7000"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "oc-lettings"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "password"

volumes:
  postgres-data:
