version: '3.10'

services:
  app:
    build:
      context: .
    environment:
      - DEBUG="1"
      - PORT="7000"
      - SECRET_KEY
      - SENTRY_DNS="https://19dc4cfc565f4f36bad78168c9e7a646@o4503968575586304.ingest.sentry.io/4503968578404352"
      - DATABASE_URL="postgres://app:password@db:5432/oc-lettings"
    image: xevan/oc-lettings-repo:latest
    ports:
      - "7000:7000"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "oc-lettings"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "password"

volumes:
  postgres-data:
