version: 2.1

orbs:
  python: circleci/python@2.1.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

heroku-auth: &heroku-auth
  auth:
    url: registry.heroku.com
    username: $HEROKU_EMAIL
    email: $HEROKU_EMAIL
    password: $HEROKU_PASSWORD

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest oc_lettings

  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt
      - run:
          name: Run flake8
          command: python -m flake8 oc_lettings

  x_and_test:
    docker:
      - image: xevan/oc-lettings-repo:$CIRCLE_SHA1
        <<: *docker-auth
        environment:
          DEBUG: 1
          SENTRY_DNS: $SENTRY_DNS
          DATABASE_URL: "postgres://app:somemdp@localhost:5432/circle_test?sslmode=disable"
          USE_DOCKER: no
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: app
          POSTGRES_DB: circle_test
          POSTGREST_PASSWORD: somemdp
          PORT: 5000
          PYTHONPATH: ./oc_lettings:$PYTHONPATH
        <<: *docker-auth
    steps:
      - checkout
      - run:
          name: Init Bd
          command: pwd && ls -l && python oc_lettings/manage.py init
      - run:
          name: Test
          command: cd oc_lettings && python -m pytest
      - run:
          name: Start Serveur
          command: gunicorn --chdir /home/CircleCI/project/oc_lettings --pythonpath /home/CircleCI/project/oc_lettings --env DJANGO_SETTINGS_MODULE=oc_lettings.settings oc_lettings.wsgi:application --bind=$PORT

  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
        - checkout
        - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - run: docker build -t xevan/oc-lettings-repo:$CIRCLE_SHA1 .
        - run: docker push xevan/oc-lettings-repo:$CIRCLE_SHA1

  compose_and_test:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      DEBUG: 1
      PORT: 7000
      SENTRY_DNS: $SENTRY_DNS
      DATABASE_URL: "postgres://marcel:password@db:5432/circleci_test"
      POSTGRES_USER: marcel
      POSTGRES_DB: circleci_test
      POSTGRES_PASSWORD: password
    steps:
        - checkout
        - run: export DEBUG
        - run: export PORT
        - run: export SENTRY_DNS
        - run: export DATABASE_URL
        - run: export POSTGRES_USER
        - run: export POSTGRES_DB
        - run: export POSTGRES_PASSWORD
        - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - run: docker pull xevan/oc-lettings-repo:$CIRCLE_SHA1
        - run: docker run -e SENTRY_DNS=$SENTRY_DNS xevan/oc-lettings-repo:$CIRCLE_SHA1 export SENTRY_DNS
        - run: docker run -e DATABASE_URL=$DATABASE_URL xevan/oc-lettings-repo:$CIRCLE_SHA1 export DATABASE_URL
        - run: docker compose -f docker-compose-prod.yaml

  heroku_deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker pull xevan/oc-lettings-repo:$CIRCLE_SHA1
      - run: docker tag xevan/oc-lettings-repo:$CIRCLE_SHA1 registry.heroku.com/oc-lettings-oc/web
      - run: docker push registry.heroku.com/oc-lettings-oc/web
      # install CLI
      - run: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push --app=oc-lettings-oc web


# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  base:
    jobs:
      - test
      - lint:
          filters:
            branches:
              only:
                - master
                - dev
      - build:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
      - compose_and_test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - heroku_deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - compose_and_test
  test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
      - compose_and_test:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci-project-setup
      - heroku_deploy:
          requires:
            - compose_and_test
          filters:
            branches:
              only:
                - circleci-project-setup

