version: 2.1

orbs:
  python: circleci/python@2.1.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

heroku-auth: &heroku-auth
  auth:
    url: registry.heroku.com
    username: $HEROKU_EMAIL
    email: $HEROKU_EMAIL
    password: $HEROKU_PASSWORD

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest oc-lettings

  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt
      - run:
          name: Run flake8
          command: python -m flake8 oc-lettings

  build_and_test:
    docker:
      - image: xevan/oc-lettings-repo:$CIRCLE_SHA1
        <<: *docker-auth
        environment:
          DATABASE_URL: "postgres://app:supermdp@db:5432/oc-lettings"
          USE_DOCKER: no
      - image: cimg/postgres:14.1:lts
        <<: *docker-auth
        environment:
          POSTGRES_USER: app
          POSTGRES_DB: oc-lettings
    steps:
      - checkout

  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
        - checkout
        - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          docker build -t xevan/oc-lettings-repo:$CIRCLE_SHA1 .
        - run: docker push xevan/oc-lettings-repo:$CIRCLE_SHA1

  compose_and_test:
    machine:
      image: ubuntu-2204:2022.04.2
      environment:
        DATABASE_URL: "postgres://app:supermdp@db:5432/oc-lettings"
        POSTGRES_USER: app
        POSTGRES_DB: oc-lettings
    steps:
        - checkout
        - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          docker compose up

  heroku_deploy:
    docker:
      - image: xevan/oc-lettings-repo:$CIRCLE_SHA1
      <<: *docker-auth
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          docker pull xevan/oc-lettings-repo:$CIRCLE_SHA1
          docker tag xevan/oc-lettings-repo:$CIRCLE_SHA1 release
          docker push release
          heroku container:release web release


# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  base:
    jobs:
      - test
      - lint:
          filters:
            branches:
              only:
                - master
                - dev
      - build:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
      - compose_and_test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - heroku_deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - compose_and_test
  test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup

