# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs: https://circleci.com/docs/2.0/orb-intro/
orbs:
  #  https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1


# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  testing:
    # https://circleci.com/docs/2.0/executor-types/
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest oc-lettings

  linting:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt
      - run:
          name: Run flake8
          command: python -m flake8 oc-lettings

  build_test_image:
    docker:
      - image: cimg/python:lts
    steps:
      - checkout

  testing_functional:
    docker:
      - image: cimg/python:lts
    steps:
      - checkout

  build_heroku_image:
    docker:
      - image: cimg/python:lts
    steps:
      - checkout

  heroku_deploy:
    docker:
      - image: cimg/python:lts
    steps:
      - checkout


# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:

  docker:
    jobs:
      - testing
      - linting:
          filters:
            branches:
              only:
                - master
      - build_test_image:
          requires:
            - testing
            - linting
          filters:
            branches:
              only:
                - master
      - testing_functional:
          requires:
            - build_test_image
          filters:
            branches:
              only:
                - master
      - build_heroku_image:
          filters:
            branches:
              only:
                - master
          requires:
              - testing_functional
      - heroku_deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build_heroku_image
