version: 2.1

orbs:
  python: circleci/python@2.1.1

docker-auth: &docker-auth
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

heroku-auth: &heroku-auth
  auth:
    url: registry.heroku.com
    username: $HEROKU_EMAIL
    email: $HEROKU_EMAIL
    password: $HEROKU_PASSWORD

jobs:
  test_sqlite:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest oc_lettings

  test:
    docker:
      - image: cimg/python:3.10.0
        <<: *docker-auth
        environment:
          BASH_ENV: /etc/profile
          DEBUG: 1
          SENTRY_DNS: $SENTRY_DNS
          DATABASE_URL: "postgres://app:somemdp@localhost:5432/circle_test?sslmode=disable"
          USE_DOCKER: no
          PATH: venv/bin:/etc/profile:$PATH
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: app
          POSTGRES_DB: circle_test
          POSTGREST_PASSWORD: somemdp
          PORT: 5432
        <<: *docker-auth
    steps:
      - checkout
      - run: python3 -m venv venv &&\
             sudo sh -c "echo '. venv/bin/activate' >> $BASH_ENV" &&\
             pip install -r requirements/dev.txt
      - run:
          name: Init Bd
          command: pwd && ls -l && python oc_lettings/manage.py init
      - run:
          name: Test
          command: python -m pytest oc_lettings

  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run flake8
          command: cd oc_lettings && python -m flake8 oc_lettings

  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
        - checkout
        - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - run: docker build -t xevan/oc-lettings-repo:$CIRCLE_SHA1 .
        - run: docker push xevan/oc-lettings-repo:$CIRCLE_SHA1

  compose_and_test:
    machine:
      image: ubuntu-2204:2022.04.2
    environment:
      BASH_ENV: /etc/profile
      DEBUG: 1
      PORT: 7000
      DATABASE_URL: "postgres://app:password@db:5432/oc-lettings"
      POSTGRES_USER: app
      POSTGRES_DB: oc-lettings
      POSTGRES_PASSWORD: password
    steps:
        - checkout
        - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - run: docker pull xevan/oc-lettings-repo:$CIRCLE_SHA1
        - run: sudo sh -c "echo 'export POSTGRES_DB=${POSTGRES_DB}' >> $BASH_ENV"
        - run: sudo sh -c "echo 'export SENTRY_DNS=${SENTRY_DNS}' >> $BASH_ENV"
        - run: sudo sh -c "echo 'export SECRET_KEY=${SECRET_KEY}' >> $BASH_ENV"
        - run: docker compose -f docker-compose-prod.yaml up -d
        - run: docker compose -f docker-compose-prod.yaml exec app python manage.py init

  heroku_deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run: echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker pull xevan/oc-lettings-repo:$CIRCLE_SHA1
      - run: docker tag xevan/oc-lettings-repo:$CIRCLE_SHA1 registry.heroku.com/oc-lettings-oc/web
      # install CLI
      - run: sudo curl https://cli-assets.heroku.com/install.sh | sh
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} docker push registry.heroku.com/oc-lettings-oc/web
      - run: HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release --app=oc-lettings-oc web


# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  base:
    jobs:
      - test
      - lint
      - build:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
      - compose_and_test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - heroku_deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - compose_and_test
