# Generated by Django 3.0 on 2022-10-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_delete_address'),
        ('lettings', '0004_auto_20221016_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letting',
        ),
    ]
