# Generated by Django 3.0 on 2022-10-16 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0004_delete_letting'),
        ('profiles', '0002_auto_20221016_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
